#gcc -o project2 -Wall -std=c99  large_asymmetric_best.c psumemory.c psumemory.h


default:
		gcc -g -std=gnu99 -o project2 -Wall -Wextra -Wno-unused-parameter large_symmetric_worst.c psumemory.c psumemory.h
		
clean:
		rm project2
